[package]
name = "text-completion"
version = "0.1.0"
edition = "2021"

[dependencies]
tc-estimator = { path = "../tc-estimator" }
crossterm = "0.28.1"

[profile.dev]
opt-level = 1           
overflow-checks = false 
